<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-A1OLLL7" failures="0" tests="6" name="NewGetPets" time="0.058" errors="1" timestamp="2022-08-30T11:59:11 IST" skipped="5">
  <testcase classname="NewGetPets" name="createReport" time="0.058">
    <error message="Cannot invoke &quot;java.util.List.forEach(java.util.function.Consumer)&quot; because &quot;this.reporterList&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.reporterList" is null
at com.aventstack.extentreports.Report.createTest(Report.java:55)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:230)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:243)
at NewGetPets.createReport(NewGetPets.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createReport -->
  <system-out/>
  <testcase classname="NewGetPets" name="testgetavailablepets" time="0.000">
    <skipped/>
  </testcase> <!-- testgetavailablepets -->
  <system-out/>
  <testcase classname="NewGetPets" name="testgetpendingpets" time="0.000">
    <skipped/>
  </testcase> <!-- testgetpendingpets -->
  <system-out/>
  <testcase classname="NewGetPets" name="testsold" time="0.000">
    <skipped/>
  </testcase> <!-- testsold -->
  <system-out/>
  <testcase classname="NewGetPets" name="invalidstatus" time="0.000">
    <skipped/>
  </testcase> <!-- invalidstatus -->
  <system-out/>
  <testcase classname="NewGetPets" name="blankstatus" time="0.000">
    <skipped/>
  </testcase> <!-- blankstatus -->
  <system-out/>
</testsuite> <!-- NewGetPets -->
